# Generated by Django 4.2.5 on 2023-09-14 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
                'db_table': 'pereval_coords',
            },
        ),
        migrations.CreateModel(
            name='PerevalAdded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=10, verbose_name='Вид объекта')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('other_titles', models.CharField(blank=True, max_length=255, verbose_name='Прочие наименования')),
                ('connect', models.TextField(blank=True, verbose_name='Соединение')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('level_winter', models.CharField(blank=True, max_length=10, verbose_name='Сложность - Зима')),
                ('level_spring', models.CharField(blank=True, max_length=10, verbose_name='Сложность - Весна')),
                ('level_summer', models.CharField(blank=True, max_length=10, verbose_name='Сложность - Лето')),
                ('level_autumn', models.CharField(blank=True, max_length=10, verbose_name='Сложность - Осень')),
                ('status', models.CharField(choices=[('new', 'Новая запись'), ('pending', 'Ожидает подтверждения'), ('accepted', 'Подтверждено'), ('rejected', 'Отказано')], default='new', verbose_name='Статус проверки записи')),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords', verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'db_table': 'pereval_added',
            },
        ),
        migrations.CreateModel(
            name='PerevalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
            ],
        ),
        migrations.CreateModel(
            name='PerevalImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.perevaladded', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'db_table': 'pereval_images',
            },
        ),
        migrations.AddField(
            model_name='perevaladded',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.perevaluser', verbose_name='Пользователь'),
        ),
    ]
