# Generated by Django 4.2.5 on 2023-09-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coords',
            table='pereval_coords',
        ),
    ]
