# Generated by Django 4.2.5 on 2023-09-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_alter_coords_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevaladded',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('pending', 'Ожидает подтверждения'), ('accepted', 'Подтверждено'), ('rejected', 'Отказано')], default='new'),
        ),
    ]
