# Generated by Django 4.2.5 on 2023-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_alter_perevaluser_options_alter_perevalimages_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaluser',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
    ]
