# Generated by Django 4.2.5 on 2023-10-01 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_alter_perevaluser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimages',
            name='pereval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pereval.perevaladded', verbose_name='Объект'),
        ),
    ]
