# Generated by Django 4.2.5 on 2023-10-01 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0004_alter_perevalimages_pereval'),
    ]

    operations = [
        migrations.AddField(
            model_name='perevalimages',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='perevalimages',
            name='pereval',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.perevaladded', verbose_name='Объект'),
        ),
    ]
