# Generated by Django 4.2.5 on 2023-10-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_perevalimages_title_alter_perevalimages_pereval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perevaluser',
            name='username',
        ),
        migrations.AddField(
            model_name='perevaluser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='perevaluser',
            name='sur_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='perevaluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
    ]
